### ISSUE TITLE
No images on public wishlist

### ISSUE THREAD

**Issue by Rupp3r** [aunefyren/poenskelisten#24]
I can not seem to get images to show on publicly shared wishlists. I do not seem to have any errors. It shows fine when logged in.
Hope you can help.

**Comment by aunefyren** [comment]
Hey, yes currently you cannot load images on public wishlists. This is because the endpoint currently has login validation so the public visitors would not be able to see the images. I will fix this in the next update.

**Comment by Rupp3r** [comment]
Works great! 👍🏻

My family loves you and me too 🙏🏻 
Thank you so much 10/10!

**Comment by aunefyren** [comment]
Added in v2.0.5.

**Comment by aunefyren** [comment]
> Works great! 👍🏻
> 
> My family loves you and me too 🙏🏻 Thank you so much 10/10!

You are too kind <3
