### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by Shahin-rmz** [aunefyren/poenskelisten#5]
Hi, 
I just saw the project. it seems very promising.
Thanks for adding value to the world with this piece of code.
Just a question, I may self host the project on Raspberry pi (ARMx64 chip).
I just need to use `mariadb` instead of `mysql` right?
I think rest will work!

**Comment by aunefyren** [comment]
ARM64 is supported. Either use the Docker image, an ARM64 release on the release page, or compile the files using `go build`. 

Currently it only works with `mysql`, but I am pretty sure only a small change is needed to support `mariadb`.

**Comment by Shahin-rmz** [comment]
You were right. with pretty small changes I could manage to self host my wishlist.
Thanks so much for such a great idea.
