### ISSUE TITLE
Support for public whishlists ?

### ISSUE THREAD

**Issue by a-camacho** [aunefyren/poenskelisten#6]
Hi,

Would it be possible to share a wishlist publicly ?

Thanks a lot !

**Comment by aunefyren** [comment]
That could certainly be possible. I can't see a way to keep the wish-claiming feature though. Would it still be helpful without claiming?

**Comment by a-camacho** [comment]
> That could certainly be possible. I can't see a way to keep the wish-claiming feature though. Would it still be helpful without claiming?

Yes, i did not even see this feature, but I am not thinking about using it.

My use case would be to be able to share whishlists with people, and I could remove an item manually as soon as someone tells me that this is the gift they want to give.
