### ISSUE TITLE
Privacy Question

### ISSUE THREAD

**Issue by Shahin-rmz** [aunefyren/poenskelisten#7]
Poenskelisten is awesome.
it solves a problem of mine.
I adjust my todos with my wishes.
Thanks for making and maintaining it.
just a small question, how will be a data that send to you as developer look like?
I want to see which sorts of data will be shared with you publicly :D 
Thanks

**Comment by aunefyren** [comment]
Hey, thanks for the feedback and compliments. Thrilled people have a use for this project.

Regarding data, nothing is currently sent anywhere and I have no plans to gather any metrics. The front end speaks to the back end, and the back end hosts the API and speaks to the database. There is no outgoing connection in the source code except SMTP requests to send e-mails using your chosen server.

If I for any reason planned on adding external outgoing user metrics (I can see how large projects find this data helpful) I would make this optional. I hope that answers your question.

**Comment by Shahin-rmz** [comment]
> I hope that answers your question.

You answered my question completely.
Close as satisfied.
